package com.github.pavponn.fsds

import com.github.pavponn.message.Message
import com.github.pavponn.utils.ProcessId
import com.github.pavponn.utils.Signature
import com.github.pavponn.utils.Timestamp

/**
 * @author pavponn
 */
interface ForwardSecureDigitalSignatures {

    /**
     * Sets local st to timestamp if st is less than st.
     */
    fun updateFSKey(timestamp: Timestamp)

    /**
     * Returns a signature for a message m and timestamp t if t > st otherwise it should throw.
     */
    fun signFS(message: Message, timestamp: Timestamp): Signature

    /**
     * Returns true if signature was generated by the process using signFS(m, t), otherwise returns false.
     */
    fun verifyFS(message: Message, process: ProcessId, signature: Signature, timestamp: Timestamp): Boolean
}
